name: Build and publish test environment

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch: { }
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: "Build blog"
        run: |
          git clone https://github.com/codemzy/static-blog
          rm -rf static-blog/posts/*
          rm -rf static-blog/settings/*
          mv posts/* static-blog/posts
          mv settings/* static-blog/settings
          cd static-blog
          npm install
          npm audit fix
          npm run build
          mkdir static-blog/img
          mv img/*.png static-blog/img
          mv img/*.jpg static-blog/img
          mv img/*.jpeg static-blog/img
          mv img/*.gif static-blog/img
      - name: "Deploy"
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: deploy
          folder: static-blog/dist